type User {
    _id: ID
    name: String
    email: String
    password: String
    is_Active: Boolean 
    posts: [Post]
    error: String
}

type Query {
    users: [User!]!
    user(id: ID!): User!
}

input UserInput {
    name: String!
    email: String!
    password: String!
    is_Active: Boolean!
}

type Mutation {
    createUser(data: UserInput!): User
    updateUser(id: ID! , data: UserInput!): User!
    deleteUser(id: ID!): Boolean
}